/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ServicesInstallationRouteImport } from './routes/services.installation'
import { Route as ServicesDesignRouteImport } from './routes/services.design'
import { Route as ProductsWagonsRouteImport } from './routes/products.wagons'
import { Route as ProductsSntRouteImport } from './routes/products.snt'
import { Route as ProductsElectricLocomotiveRouteImport } from './routes/products.electric-locomotive'
import { Route as ProductsCoachesRouteImport } from './routes/products.coaches'
import { Route as ProductsWagonsIndexRouteImport } from './routes/products.wagons.index'
import { Route as ProductsSntIndexRouteImport } from './routes/products.snt.index'
import { Route as ProductsElectricLocomotiveIndexRouteImport } from './routes/products.electric-locomotive.index'
import { Route as ProductsWagonsWliRouteImport } from './routes/products.wagons.wli'
import { Route as ProductsWagonsAhabdRouteImport } from './routes/products.wagons.ahabd'
import { Route as ProductsSntRdpmsRouteImport } from './routes/products.snt.rdpms'
import { Route as ProductsSntIpsRouteImport } from './routes/products.snt.ips'
import { Route as ProductsElectricLocomotiveSimulatorsRouteImport } from './routes/products.electric-locomotive.simulators'
import { Route as ProductsElectricLocomotiveIftRouteImport } from './routes/products.electric-locomotive.ift'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ServicesInstallationRoute = ServicesInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDesignRoute = ServicesDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsWagonsRoute = ProductsWagonsRouteImport.update({
  id: '/wagons',
  path: '/wagons',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSntRoute = ProductsSntRouteImport.update({
  id: '/snt',
  path: '/snt',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsElectricLocomotiveRoute =
  ProductsElectricLocomotiveRouteImport.update({
    id: '/electric-locomotive',
    path: '/electric-locomotive',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsCoachesRoute = ProductsCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsWagonsIndexRoute = ProductsWagonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsWagonsRoute,
} as any)
const ProductsSntIndexRoute = ProductsSntIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSntRoute,
} as any)
const ProductsElectricLocomotiveIndexRoute =
  ProductsElectricLocomotiveIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProductsElectricLocomotiveRoute,
  } as any)
const ProductsWagonsWliRoute = ProductsWagonsWliRouteImport.update({
  id: '/wli',
  path: '/wli',
  getParentRoute: () => ProductsWagonsRoute,
} as any)
const ProductsWagonsAhabdRoute = ProductsWagonsAhabdRouteImport.update({
  id: '/ahabd',
  path: '/ahabd',
  getParentRoute: () => ProductsWagonsRoute,
} as any)
const ProductsSntRdpmsRoute = ProductsSntRdpmsRouteImport.update({
  id: '/rdpms',
  path: '/rdpms',
  getParentRoute: () => ProductsSntRoute,
} as any)
const ProductsSntIpsRoute = ProductsSntIpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => ProductsSntRoute,
} as any)
const ProductsElectricLocomotiveSimulatorsRoute =
  ProductsElectricLocomotiveSimulatorsRouteImport.update({
    id: '/simulators',
    path: '/simulators',
    getParentRoute: () => ProductsElectricLocomotiveRoute,
  } as any)
const ProductsElectricLocomotiveIftRoute =
  ProductsElectricLocomotiveIftRouteImport.update({
    id: '/ift',
    path: '/ift',
    getParentRoute: () => ProductsElectricLocomotiveRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/products/coaches': typeof ProductsCoachesRoute
  '/products/electric-locomotive': typeof ProductsElectricLocomotiveRouteWithChildren
  '/products/snt': typeof ProductsSntRouteWithChildren
  '/products/wagons': typeof ProductsWagonsRouteWithChildren
  '/services/design': typeof ServicesDesignRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/products/electric-locomotive/ift': typeof ProductsElectricLocomotiveIftRoute
  '/products/electric-locomotive/simulators': typeof ProductsElectricLocomotiveSimulatorsRoute
  '/products/snt/ips': typeof ProductsSntIpsRoute
  '/products/snt/rdpms': typeof ProductsSntRdpmsRoute
  '/products/wagons/ahabd': typeof ProductsWagonsAhabdRoute
  '/products/wagons/wli': typeof ProductsWagonsWliRoute
  '/products/electric-locomotive/': typeof ProductsElectricLocomotiveIndexRoute
  '/products/snt/': typeof ProductsSntIndexRoute
  '/products/wagons/': typeof ProductsWagonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/terms': typeof TermsRoute
  '/products/coaches': typeof ProductsCoachesRoute
  '/services/design': typeof ServicesDesignRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/products/electric-locomotive/ift': typeof ProductsElectricLocomotiveIftRoute
  '/products/electric-locomotive/simulators': typeof ProductsElectricLocomotiveSimulatorsRoute
  '/products/snt/ips': typeof ProductsSntIpsRoute
  '/products/snt/rdpms': typeof ProductsSntRdpmsRoute
  '/products/wagons/ahabd': typeof ProductsWagonsAhabdRoute
  '/products/wagons/wli': typeof ProductsWagonsWliRoute
  '/products/electric-locomotive': typeof ProductsElectricLocomotiveIndexRoute
  '/products/snt': typeof ProductsSntIndexRoute
  '/products/wagons': typeof ProductsWagonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/products/coaches': typeof ProductsCoachesRoute
  '/products/electric-locomotive': typeof ProductsElectricLocomotiveRouteWithChildren
  '/products/snt': typeof ProductsSntRouteWithChildren
  '/products/wagons': typeof ProductsWagonsRouteWithChildren
  '/services/design': typeof ServicesDesignRoute
  '/services/installation': typeof ServicesInstallationRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/products/electric-locomotive/ift': typeof ProductsElectricLocomotiveIftRoute
  '/products/electric-locomotive/simulators': typeof ProductsElectricLocomotiveSimulatorsRoute
  '/products/snt/ips': typeof ProductsSntIpsRoute
  '/products/snt/rdpms': typeof ProductsSntRdpmsRoute
  '/products/wagons/ahabd': typeof ProductsWagonsAhabdRoute
  '/products/wagons/wli': typeof ProductsWagonsWliRoute
  '/products/electric-locomotive/': typeof ProductsElectricLocomotiveIndexRoute
  '/products/snt/': typeof ProductsSntIndexRoute
  '/products/wagons/': typeof ProductsWagonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/services'
    | '/terms'
    | '/products/coaches'
    | '/products/electric-locomotive'
    | '/products/snt'
    | '/products/wagons'
    | '/services/design'
    | '/services/installation'
    | '/products/'
    | '/services/'
    | '/products/electric-locomotive/ift'
    | '/products/electric-locomotive/simulators'
    | '/products/snt/ips'
    | '/products/snt/rdpms'
    | '/products/wagons/ahabd'
    | '/products/wagons/wli'
    | '/products/electric-locomotive/'
    | '/products/snt/'
    | '/products/wagons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/terms'
    | '/products/coaches'
    | '/services/design'
    | '/services/installation'
    | '/products'
    | '/services'
    | '/products/electric-locomotive/ift'
    | '/products/electric-locomotive/simulators'
    | '/products/snt/ips'
    | '/products/snt/rdpms'
    | '/products/wagons/ahabd'
    | '/products/wagons/wli'
    | '/products/electric-locomotive'
    | '/products/snt'
    | '/products/wagons'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/projects'
    | '/services'
    | '/terms'
    | '/products/coaches'
    | '/products/electric-locomotive'
    | '/products/snt'
    | '/products/wagons'
    | '/services/design'
    | '/services/installation'
    | '/products/'
    | '/services/'
    | '/products/electric-locomotive/ift'
    | '/products/electric-locomotive/simulators'
    | '/products/snt/ips'
    | '/products/snt/rdpms'
    | '/products/wagons/ahabd'
    | '/products/wagons/wli'
    | '/products/electric-locomotive/'
    | '/products/snt/'
    | '/products/wagons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/services/installation': {
      id: '/services/installation'
      path: '/installation'
      fullPath: '/services/installation'
      preLoaderRoute: typeof ServicesInstallationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/design': {
      id: '/services/design'
      path: '/design'
      fullPath: '/services/design'
      preLoaderRoute: typeof ServicesDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/wagons': {
      id: '/products/wagons'
      path: '/wagons'
      fullPath: '/products/wagons'
      preLoaderRoute: typeof ProductsWagonsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/snt': {
      id: '/products/snt'
      path: '/snt'
      fullPath: '/products/snt'
      preLoaderRoute: typeof ProductsSntRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/electric-locomotive': {
      id: '/products/electric-locomotive'
      path: '/electric-locomotive'
      fullPath: '/products/electric-locomotive'
      preLoaderRoute: typeof ProductsElectricLocomotiveRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/coaches': {
      id: '/products/coaches'
      path: '/coaches'
      fullPath: '/products/coaches'
      preLoaderRoute: typeof ProductsCoachesRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/wagons/': {
      id: '/products/wagons/'
      path: '/'
      fullPath: '/products/wagons/'
      preLoaderRoute: typeof ProductsWagonsIndexRouteImport
      parentRoute: typeof ProductsWagonsRoute
    }
    '/products/snt/': {
      id: '/products/snt/'
      path: '/'
      fullPath: '/products/snt/'
      preLoaderRoute: typeof ProductsSntIndexRouteImport
      parentRoute: typeof ProductsSntRoute
    }
    '/products/electric-locomotive/': {
      id: '/products/electric-locomotive/'
      path: '/'
      fullPath: '/products/electric-locomotive/'
      preLoaderRoute: typeof ProductsElectricLocomotiveIndexRouteImport
      parentRoute: typeof ProductsElectricLocomotiveRoute
    }
    '/products/wagons/wli': {
      id: '/products/wagons/wli'
      path: '/wli'
      fullPath: '/products/wagons/wli'
      preLoaderRoute: typeof ProductsWagonsWliRouteImport
      parentRoute: typeof ProductsWagonsRoute
    }
    '/products/wagons/ahabd': {
      id: '/products/wagons/ahabd'
      path: '/ahabd'
      fullPath: '/products/wagons/ahabd'
      preLoaderRoute: typeof ProductsWagonsAhabdRouteImport
      parentRoute: typeof ProductsWagonsRoute
    }
    '/products/snt/rdpms': {
      id: '/products/snt/rdpms'
      path: '/rdpms'
      fullPath: '/products/snt/rdpms'
      preLoaderRoute: typeof ProductsSntRdpmsRouteImport
      parentRoute: typeof ProductsSntRoute
    }
    '/products/snt/ips': {
      id: '/products/snt/ips'
      path: '/ips'
      fullPath: '/products/snt/ips'
      preLoaderRoute: typeof ProductsSntIpsRouteImport
      parentRoute: typeof ProductsSntRoute
    }
    '/products/electric-locomotive/simulators': {
      id: '/products/electric-locomotive/simulators'
      path: '/simulators'
      fullPath: '/products/electric-locomotive/simulators'
      preLoaderRoute: typeof ProductsElectricLocomotiveSimulatorsRouteImport
      parentRoute: typeof ProductsElectricLocomotiveRoute
    }
    '/products/electric-locomotive/ift': {
      id: '/products/electric-locomotive/ift'
      path: '/ift'
      fullPath: '/products/electric-locomotive/ift'
      preLoaderRoute: typeof ProductsElectricLocomotiveIftRouteImport
      parentRoute: typeof ProductsElectricLocomotiveRoute
    }
  }
}

interface ProductsElectricLocomotiveRouteChildren {
  ProductsElectricLocomotiveIftRoute: typeof ProductsElectricLocomotiveIftRoute
  ProductsElectricLocomotiveSimulatorsRoute: typeof ProductsElectricLocomotiveSimulatorsRoute
  ProductsElectricLocomotiveIndexRoute: typeof ProductsElectricLocomotiveIndexRoute
}

const ProductsElectricLocomotiveRouteChildren: ProductsElectricLocomotiveRouteChildren =
  {
    ProductsElectricLocomotiveIftRoute: ProductsElectricLocomotiveIftRoute,
    ProductsElectricLocomotiveSimulatorsRoute:
      ProductsElectricLocomotiveSimulatorsRoute,
    ProductsElectricLocomotiveIndexRoute: ProductsElectricLocomotiveIndexRoute,
  }

const ProductsElectricLocomotiveRouteWithChildren =
  ProductsElectricLocomotiveRoute._addFileChildren(
    ProductsElectricLocomotiveRouteChildren,
  )

interface ProductsSntRouteChildren {
  ProductsSntIpsRoute: typeof ProductsSntIpsRoute
  ProductsSntRdpmsRoute: typeof ProductsSntRdpmsRoute
  ProductsSntIndexRoute: typeof ProductsSntIndexRoute
}

const ProductsSntRouteChildren: ProductsSntRouteChildren = {
  ProductsSntIpsRoute: ProductsSntIpsRoute,
  ProductsSntRdpmsRoute: ProductsSntRdpmsRoute,
  ProductsSntIndexRoute: ProductsSntIndexRoute,
}

const ProductsSntRouteWithChildren = ProductsSntRoute._addFileChildren(
  ProductsSntRouteChildren,
)

interface ProductsWagonsRouteChildren {
  ProductsWagonsAhabdRoute: typeof ProductsWagonsAhabdRoute
  ProductsWagonsWliRoute: typeof ProductsWagonsWliRoute
  ProductsWagonsIndexRoute: typeof ProductsWagonsIndexRoute
}

const ProductsWagonsRouteChildren: ProductsWagonsRouteChildren = {
  ProductsWagonsAhabdRoute: ProductsWagonsAhabdRoute,
  ProductsWagonsWliRoute: ProductsWagonsWliRoute,
  ProductsWagonsIndexRoute: ProductsWagonsIndexRoute,
}

const ProductsWagonsRouteWithChildren = ProductsWagonsRoute._addFileChildren(
  ProductsWagonsRouteChildren,
)

interface ProductsRouteChildren {
  ProductsCoachesRoute: typeof ProductsCoachesRoute
  ProductsElectricLocomotiveRoute: typeof ProductsElectricLocomotiveRouteWithChildren
  ProductsSntRoute: typeof ProductsSntRouteWithChildren
  ProductsWagonsRoute: typeof ProductsWagonsRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCoachesRoute: ProductsCoachesRoute,
  ProductsElectricLocomotiveRoute: ProductsElectricLocomotiveRouteWithChildren,
  ProductsSntRoute: ProductsSntRouteWithChildren,
  ProductsWagonsRoute: ProductsWagonsRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesDesignRoute: typeof ServicesDesignRoute
  ServicesInstallationRoute: typeof ServicesInstallationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDesignRoute: ServicesDesignRoute,
  ServicesInstallationRoute: ServicesInstallationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
